"""2023_09_26-18_38

Revision ID: 04d076f41d21
Revises: 72a37135b122
Create Date: 2023-09-26 18:40:40.768234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d076f41d21'
down_revision: Union[str, None] = '72a37135b122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'xg',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'xg',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
