"""inital

Revision ID: 1e7a3c4db864
Revises: 
Create Date: 2023-09-09 15:20:51.982026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7a3c4db864'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('victory', sa.Boolean(), nullable=False),
    sa.Column('minutes', sa.String(length=3), nullable=False),
    sa.Column('seconds', sa.String(length=2), nullable=False),
    sa.Column('goals', sa.SmallInteger(), nullable=False),
    sa.Column('ball_possession', sa.SmallInteger(), nullable=False),
    sa.Column('strikes', sa.SmallInteger(), nullable=False),
    sa.Column('xg', sa.Float(precision=1), nullable=False),
    sa.Column('passes', sa.SmallInteger(), nullable=False),
    sa.Column('selections', sa.SmallInteger(), nullable=False),
    sa.Column('successful_selections', sa.SmallInteger(), nullable=False),
    sa.Column('interceptions', sa.SmallInteger(), nullable=False),
    sa.Column('saves', sa.SmallInteger(), nullable=False),
    sa.Column('violations', sa.SmallInteger(), nullable=False),
    sa.Column('offsides', sa.SmallInteger(), nullable=False),
    sa.Column('corners', sa.SmallInteger(), nullable=False),
    sa.Column('free_kicks', sa.SmallInteger(), nullable=False),
    sa.Column('penalty_kicks', sa.SmallInteger(), nullable=False),
    sa.Column('yellow_cards', sa.SmallInteger(), nullable=False),
    sa.Column('red_cards', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('player')
    op.drop_table('user')
    # ### end Alembic commands ###
