"""2023_09_13-19_12

Revision ID: a3eec3344904
Revises: 1f1f75075c61
Create Date: 2023-09-13 19:12:48.131512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3eec3344904'
down_revision: Union[str, None] = '1f1f75075c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'xg',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'xg',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
